# Generated by Django 4.2 on 2024-06-18 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_no'], name='accounts_ac_account_0fb751_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['phone'], name='accounts_ac_phone_f1755d_idx'),
        ),
    ]
